Finished profile tests
HackIllinois/adonix pull request #102
Opened 2023-10-19 21:58 UTC by akulsharma1

- Added `profile-router.test.ts` 
- Bug fixes to `profile-router.ts`

2023-10-19 22:40 UTC, Timothy-Gonzalez commented
Several notes (not sure if significant, cc @AydanPirani for final review):

[Coverage report](https://github.com/HackIllinois/adonix/actions/runs/6580703800/job/17879249657?pr=102) for profile is as follows:
```
src/services/profile     |    83.8 |    73.91 |      25 |    83.8 |                                                                                                                                         
  profile-formats.ts     |   77.77 |       25 |     100 |   77.77 | 11-12,15-16,24-25                                                                                                                       
  profile-lib.ts         |   55.81 |      100 |       0 |   55.81 | 12-18,25-27,35-43                                                                                                            
  profile-router.ts      |   88.65 |    84.21 |     100 |   88.65 | 53-77,166-167,228-229,244-246
```

Not covered by tests:
- profile-router.ts
  - 55-77: `GET /leaderboard/` - no idea how this works or if this should be tested yet
  - 166-167: Redirect condition when no user id, prob not easy to test but should consider checking
  - 228-229: Validation check for profile, should test this by sending bad data
  - 244-246: Check for error handling of failed create, probably not needed to test
- profile-formats.ts
  - We could add tests for this, but shouldn't as we should use something like zod instead, re: #104
- profile-lib.ts
  - 12-18: castLeaderboardEntries: used in `GET /leaderboard/`, will be covered by profile router tests
  - 25-27: isValidLimit: used in `GET /leaderboard/`, will be covered by profile router tests
  - 35-43: updatePoints: not used at all currently

All in all, pretty good coverage!

Some things I'd like to see tested:
- [ ] Post as a user (unauthorized user doesn't need to be tested, probably switch this out)
  - Basically, regular users can't edit their profile
- Can probably remove unauthorized user tests (called invalid user) as these will be tested in auth middleware

Other misc things / nitpicks:
- Can we rename "invalid user" to something more specifical
  - for example: `it("delete with a user that doesn't exist")` -> `it("fails to delete with a non-attendee user")`
  - Try to make it a sentence you can read basically

This is a great start though, great job!

2023-10-20 18:23 UTC, AydanPirani commented
@Timothy-Gonzalez  @akulsharma1 


### Leaderboard 
> GET /leaderboard/ - no idea how this works or if this should be tested yet

> 12-18: castLeaderboardEntries: used in GET /leaderboard/, will be covered by profile router tests

> 25-27: isValidLimit: used in GET /leaderboard/, will be covered by profile router tests

I wrote this super basic endpoint, it should return the top limit users by points - @akulsharma1  do you think you can add some tests in for this as well?  Basically, all you need to do is:

- Add in like 3-4 users with different point values
- Check that the endpoint (no limit) returns the users in ordered point values (most to least).
- Check that the endpoint (limit 2) returns the 2 users with the highest point counts.

And maybe add in a test case to ensure that limit cannot be negative.


### Format Testing
> We could add tests for this, but shouldn't as we should use something like zod instead, re: https://github.com/HackIllinois/adonix/issues/104

Yeah, dw about testing the actual "isValidformat" for now, just make sure that it throws if it gets a bad input.

### Role Stuff 

> Can probably remove unauthorized user tests (called invalid user) as these will be tested in auth middleware

Yup, dw about testing with roles that don't have any perms - just test that each branch of hasElevatedPerms/hasStaffPerms/hasAdminPerms gets tested.

2023-10-20 18:26 UTC, AydanPirani reviewed
it's making me review, but please reference above comments! I'm good with this once you get through the checkboxes + if @Timothy-Gonzalez  is happy. with it

2023-10-22 19:04 UTC, Timothy-Gonzalez requested changes
Looks great! A few small nps to move duplicated code out of tests & into variables & beforeEach hooks, but otherwise great job!

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets with an attendee that doesn't exist", async () => {
np: `it("gets with an attendee that doesn't exist")` -> `it("fails to get a profile that doesn't exist")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets an attendee that exists", async () => {
np: `it("gets an attendee that exist")` -> `it("gets a profile that exists")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets without a :USERID", async () => {
np: `it("gets without a :USERID")` -> `it("fails with no id provided")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +        await Models.AttendeeProfile.create({
General overall thing: you're duplicating this same creation of an AttendeeProfile, make this attendee a variable (see [my pr](https://github.com/HackIllinois/adonix/pull/105) if you aren't sure the proper way to do this), also could probably use a beforeEach (also see [my pr](https://github.com/HackIllinois/adonix/pull/105))

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets with a user", async () => {
np: `it("gets with a user")` -> `it("fails to get a profile as a user")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets with an admin", async () => {
np: `it("gets with an admin")` -> `it("gets a profile as an admin")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets a user that doesnt exist", async () => {
np: `it("gets a user that doesnt exist")` -> `it("fails to get a profile that doesn't exist")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("deletes with a attendee that doesn't exist", async () => {
np: `it("deletes with a attendee that doesn't exist")` -> `it("fails to delete a profile that doesn't exist")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("deletes with a valid user", async () => {
np: `it("deletes with a valid user")` -> `it("deletes a profile")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets with no limit but only 3 entries", async () => {
np: `it("gets with no limit but only 3 entries")` -> `it("gets 3 entries when no limit is set")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets with no limit & more entries in db than the max query limit", async () => {
np: `it("gets with no limit & more entries in db than the max query limit")` -> `it("only gets the max limit when no limit is set")`

2023-10-22 19:04 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("gets with an invalid limit", async () => {
np: `it("gets with an invalid limit")` -> `it("fails when an invalid limit is set")`

2023-10-23 01:29 UTC, Timothy-Gonzalez requested changes
few more nps that I missed

2023-10-23 01:29 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("posts for an attendee", async () => {
np: `it("posts for an attendee")` -> `it("works for an attendee")`

2023-10-23 01:29 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("posts for a user", async () => {
np: `it("posts for a user")` -> `it("fails when a profile is already created")`

2023-10-23 01:29 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
> +    it("posts with invalid data", async () => {
np: `it("posts with invalid data")` -> `it("fails when invalid data is provided")`

2023-10-25 21:19 UTC, Timothy-Gonzalez commented on src/services/profile/profile-router.test.ts
One final thing: we should use `StatusCode` enum introduced in #106 instead of constants like 200. Sorry I forgot to mention this before.

2023-10-25 21:35 UTC, Timothy-Gonzalez approved these changes
Great job! Feel free to merge!

2023-10-25 22:08 UTC, merged