Added Staff Shift endpoints
HackIllinois/adonix pull request #134
Opened 2023-12-10 03:33 UTC by akulsharma1

- added all staff shift endpoints
- NOTE: `/staff/shift` returns dummy data at the moment, we are working on bugfixing a timeout request issue but wanted to push out an MVP.

2023-12-11 07:07 UTC, lasyaneti commented on src/services/staff/staff-formats.ts
> +        startTime: 1696467600,
could you set these to be during hackillinois feb 23-26 since mobile only displays those dates

2023-12-11 07:11 UTC, lasyaneti approved these changes
LGTM for now. Just change dates for staff shifts (might need to do it manually in mongo for existing events too) and we can merge.

Eventually `GET /staff/shift` should only return events for authenticated staff.

2023-12-11 07:18 UTC, lasyaneti commented on src/services/event/event-router.ts
> +    const showAllShiftsParam: string | undefined = req.query.showAllShifts as string | undefined;
also im only testing with my token (admin) but make sure that if non-admin staff roles request showAllShifts=True, it redirects them to just shifts assigned to them - they shouldnt be able to see everything

2023-12-12 17:55 UTC, lasyaneti commented on src/services/event/event-router.ts
>  });
should be protected under admin perms

-aydan (from lasya's computer)

2023-12-12 18:04 UTC, lasyaneti requested changes

2023-12-12 18:04 UTC, lasyaneti commented on src/services/event/event-router.ts
>  });
add a check for admin perms in jwt

2023-12-12 18:04 UTC, lasyaneti commented on src/services/staff/staff-router.ts
> +        }
return hardcoded json instead

2023-12-12 18:04 UTC, lasyaneti commented on src/services/staff/staff-router.ts
> +        }
no need to run function each time

2023-12-17 14:35 UTC, AydanPirani commented on src/services/event/event-router.ts
> +    if (!hasAdminPerms(payload)) {
Why change this? All staff should be able to see staff events

Hierarchy should be like this:

non-staff: no access
staff: access to their own shifts + all general staff events
admins: access to staff shifts

2024-10-20 17:31 UTC, closed without merging