projects schema and router + adding to models
HackIllinois/adonix pull request #270
Opened 2024-10-27 21:11 UTC by Bahl-Aryan

Start of projects api

2024-10-31 02:00 UTC, aletya requested changes

2024-10-31 02:00 UTC, aletya commented on src/app.ts
> +import projectRouter from "./services/projects/projects-router";
Change "./services/projects/projects-router" to "./services/project/project-router" for consistency

2024-10-31 02:00 UTC, aletya commented on src/app.ts
> +app.use("/projects/", database, projectRouter);
Same as above, "/projects/" -> "/project/"

2024-10-31 02:00 UTC, aletya commented on src/common/models.ts
> +import { Project } from "../services/projects/projects-schema";
Same as above

2024-10-31 02:00 UTC, aletya commented on src/common/models.ts
> +    PROJECTS = "projects",
Same as above

2024-10-31 02:00 UTC, aletya commented on src/common/models.ts
> +    INFO = "projects"
This one stays plural, since it follows our DB naming convention i.e. "user_users"

2024-10-31 02:00 UTC, aletya commented on src/common/models.ts
> +    static Projects: Model<Project> = getModel(Project, Group.PROJECTS, ProjectCollection.INFO);
Change "static Projects" to "static ProjectInfo". Each of these creates a model to access a specific mongoDB collection. This one accesses the collection "project_projects", which is a bit of a special case (see user_users collection -> userInfo model).

2024-10-31 02:00 UTC, aletya commented on src/middleware/specification.ts
> +    PROJECTS = "Projects",
PROJECT = "Project"

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-router.ts
> +
small nit, switch the import statements for Role and StatusCode, since we generally keep the imports from preexisting libraries at the top.

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-router.ts
> +        role: null, //staff only endpoint
role: Role.STAFF

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-router.ts
> +        tag: Tag.PROJECTS,
see above projects->project

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-schema.ts
> +    public videoLink: string
required: false, since they might not have a video at first

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-schema.ts
> +    public videoLink: string
unless we make it so that they must have their project completely ready before submitting. so nvm this is TBD

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-schema.ts
> +export const ProjectsSchema = z
ProjectInfoSchema

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-schema.ts
> +        description: "all projects"
"A project's info"

2024-10-31 02:00 UTC, aletya commented on src/services/projects/projects-schema.ts
> +        description: "Mapping team owner's ID to their teammates' userIDs"
"A user's team/teamOwnerId"

2024-10-31 02:01 UTC, aletya commented
Solid first PR overall, thanks for getting this in so quick 👍

2024-11-02 19:39 UTC, Bahl-Aryan commented on src/services/projects/projects-schema.ts
> +export const ProjectsSchema = z
for this one, this is so we can return an array of all projects (see GET /project/list). Followed the same convention for EventsRouter. LMK if I should still change it

2024-11-10 19:08 UTC, aletya reviewed
A few nits, but LGTM overall 👍 . Hold off on merging changes in until all projects functionality is completed, including the logic for joining a team, updating one's project, removing team members, etc. We can talk about those parts during the next meeting. Also, thanks for getting so much work done on the API--- if you ever need a break/have someone take over for your tasks lmk.

2024-11-10 19:08 UTC, aletya commented on src/common/models.ts
> +    static ProjectInfo: Model<Project> = getModel(Project, Group.PROJECT, ProjectCollection.PROJECTS);
ProjectInfo -> ProjectProjects

2024-11-10 19:08 UTC, aletya commented on src/common/models.ts
> +    static ProjectMapping: Model<ProjectMappings> = getModel(ProjectMappings, Group.PROJECT, ProjectCollection.MAPPINGS);
ProjectMapping -> ProjectMappings

2024-11-10 19:08 UTC, aletya commented on src/services/project/project-router.ts
> +            return res.status(StatusCode.ClientErrorConflict).send(NoTeamFoundError);
ClientErrorConflict -> ClientErrorNotFound

2024-11-10 19:08 UTC, aletya commented on src/services/project/project-router.ts
> +            [StatusCode.ClientErrorConflict]: {
ClientErrorConflict -> ClientErrorNotFound

2024-11-10 19:08 UTC, aletya commented on src/services/project/project-router.ts
> +
Return a NoTeamFoundError if projectDetails is undefined. Even though that situation should never happen, we want to be comprehensive of all possible error cases.

2024-11-10 19:08 UTC, aletya commented on src/services/project/project-router.ts
> +        const projectDetails = await Models.ProjectInfo.findOne({ ownerId: ownerId });
ProjectInfo -> ProjectProjects

2024-11-10 19:08 UTC, aletya commented on src/services/project/project-router.ts
> +        return res.status(StatusCode.SuccessOK).send(projectDetails?.toObject());
remove ?

2024-11-10 19:08 UTC, aletya commented on src/services/project/project-router.ts
> +        // ensure teamOwner hasn't already made a team
Also check that the user isn't already mapped to a team in projectMappings.

2024-11-10 19:08 UTC, aletya commented on src/services/project/project-router.ts
> +
We'd probably also have logic for adding a projectMappings of the user to themselves, since they should be part of their own group.

2025-01-23 04:20 UTC, closed without merging