Moved puzzle answer from config to database
HackIllinois/adonix pull request #271
Opened 2024-11-03 19:06 UTC by aletya

2024-11-06 21:30 UTC, Timothy-Gonzalez requested changes
Looks good, glad we're moving answers to the database. A few things:
- Should remove the config variables so the env variables aren't rquired anymore from both `src/common/config.ts` and `.test.env`
- We should have tests for this service - it's not a huge service so this shouldn't be an issue, just want to make sure we are sure this won't break runes & riddles
- Finally, we should have a Staff only endpoint to update these answers without having to connect to the db, but that can come later

2024-11-06 21:30 UTC, Timothy-Gonzalez commented on src/services/puzzle/puzzle-router.ts
> +        const puzzleAnswer = await Models.PuzzleAnswer.findOne({ qid: qid });
np: `.findOne({ qid })` is cleaner

2024-11-13 01:09 UTC, Timothy-Gonzalez requested changes
Good overall, just need to clean up the tests a bit. A few overall things:

- [x] Don't hardcode strings, define them once and if they're already defined use it from before
- [ ] Use `beforeEach` if you're going to do something for each test
- [ ] Don't compare errors by `message` - compare by `error` (`NotFound` instead of `Couldn't find user!`. That way we can change messages without breaking tests. `error` will always be consistent.
- [x] Look at the coverage to see what is missed. According to coverage: `103-104,116-117,121-122,145-146` are all missed lines. 103-104 and 145-146 don't need to be tested, but 116-117 and 121-122 (puzzle not yet created and if puzzle is already completed) should be tested

This is very nit picky, yes, but I want the foundation of these tests to be good so that someone who extends them extends good code. Once the main tests are done, adding a few tests becomes much easier.

2024-11-13 01:09 UTC, Timothy-Gonzalez commented on src/services/puzzle/puzzle-router.test.ts
> +    userId: "bob-the-tester101010101011",
use TESTER.id instead of hardcoding

2024-11-13 01:09 UTC, Timothy-Gonzalez commented on src/services/puzzle/puzzle-router.test.ts
> +    teamName: "tester team 1",
Don't duplicate team name - use TESTER_PUZZLE_ITEM.teamName here. Might actually be better to define TESTER_CREATE_PUZZLE_ITEM first, then you can do:

```
TESTER_PUZZLE_ITEM = {
    ...TESTER_CREATED_PUZZLE_ITEM
    lastCorrect: ...,
    score: 0,
}
```
and reuse instead of duplicate

2024-11-13 01:09 UTC, Timothy-Gonzalez commented on src/services/puzzle/puzzle-router.test.ts
> +    teamName: "tester team 1",
don't duplicate everything, same as above

2024-11-13 01:09 UTC, Timothy-Gonzalez commented on src/services/puzzle/puzzle-router.test.ts
> +        await Models.PuzzleItem.create(TESTER_PUZZLE_ITEM);
Instead of creating these before each, do a beforeEach hook to create them. For the two tests you don't want them for, delete them in that test. Reduces duplication.

2024-11-13 01:09 UTC, Timothy-Gonzalez commented on src/services/puzzle/puzzle-router.test.ts
> +        expect(JSON.parse(response.text)).toHaveProperty("message", "That question doesn't exist!");
Something is up here, the error should be that the user isn't registered yet, their puzzle isn't created.

2024-11-13 01:09 UTC, Timothy-Gonzalez commented on src/services/puzzle/puzzle-router.test.ts
> +        const response = await postAsUser("/puzzle/create/").send({ teamName: "tester team 1" }).expect(StatusCode.SuccessOK);
don't hardcode teamname

2024-12-04 23:08 UTC, aletya commented on src/services/puzzle/puzzle-router.test.ts
> +        await Models.PuzzleItem.create(TESTER_PUZZLE_ITEM);
It ends up being more code though 😞. Also if we keep each items creation in its specific test, it's more readable/debugable.

2025-01-13 02:13 UTC, Timothy-Gonzalez approved these changes
LGTM

2025-01-26 16:33 UTC, merged