Dev/ananya/point shop rework
HackIllinois/adonix pull request #273
Opened 2024-12-05 03:28 UTC by ananyaanand4

point shop rework

2025-01-22 12:32 UTC, aletya requested changes

2025-01-22 12:32 UTC, aletya commented on src/services/shop/shop-router.ts
> +        const order = Math.floor(Math.random() * RAND_NUM);
use UUID to generate an order number

2025-01-22 12:32 UTC, aletya commented on src/services/shop/shop-router.ts
> +        };
The order number should also contain the userId, since we only deduct points when the order is fulfilled.

2025-01-22 12:32 UTC, aletya commented on src/services/shop/shop-router.ts
> +
Add a loop that calculates the total price of the order. Then, if the user has less points than the price, return a userInsufficientFundsError

2025-01-22 12:32 UTC, aletya commented on src/services/shop/shop-router.ts
> +
Same as above, add a loop that calculates the total price of the order. Then, if the user has less points than the price, return a userInsufficientFundsError

2025-01-22 12:32 UTC, aletya commented on src/services/shop/shop-router.ts
> +        }
1st loop: check whether there is enough of each item (return error if insufficient quantity).
2nd loop: decrement shop item quantity, and decrement user's points.

2025-01-31 16:30 UTC, Timothy-Gonzalez requested changes
This is a large review - please make sure you don't miss some of the more important comments buried in it since GitHub likes to hide the middle ones. I've summarized below, but make sure you resolve each comment as you fix them. Thanks!

Please make sure you're not deleting existing endpoints - all of the `/shop/item` endpoints are gone. That's also why the diff is so bad - you're replacing the item endpoints. Instead, just add your new ones.

Two main issues:
- We need to verify the order is still valid every time it is gotten - as quanities change over time. If the quantities in the shop aren't matching anymore, decrease the items they have. So, if they have 15 item1 in their cart, and the quantity of item1 has dropped to 10, they now have 10 item1 in their cart.
- To do so, we should be using singular operations. Calling findOne in a loop is almost always incorrect. Call find with a set of ids you want, then loop over the result. You should also do this for updates. This will reduce the db calls for a large order substantionally, improve latency, and reduce race conditions.

Finally, there's also a bit of minor code convention stuff which should be pretty easy to cleanup.

Feel free to message me if you have specific questions.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/common/config.ts
> +    NOT_FOUND: -1,
This isn't used and we shouldn't use -1 for not found

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-schemas.ts
> +// .openapi("ShopOrderArray", { example: [["item1234", "item5678"], [1, 2]] });
Don't leave commented out code - just remove it

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-schemas.ts
> +    public quantity: Array<number>;
Don't store these separately - we shouldn't be using indexing into two separate arrays. Instead, store as a dictionary from itemId to quanity. For example:
```json
{
    "item1": 5,
    "item9": 2,
}
```

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-schemas.ts
> +    instance: z.string().openapi({ example: "1x3" }),
We shouldn't need instance anymore

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-schemas.ts
> +    .openapi("Success");
Use the `SuccessResponseSchema` from common/schemas instead of re-inventing this. Also, if you're not going to pass any real response, just give the success one.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-schemas.ts
> +});
Just throw the error instead. If it's a database issue that shouldn't ever happen, etc. Just throw new Errror("Missing profile") or something like that.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-schemas.ts
> +});
This message/error doesn't make sense - if this if there's not enough of that item left in stock? This message sounds like I need to add more of that item to my cart. A better message is `"The store doesn't have that item in stock"`

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +                description: "Shop Item DNE",
Don't use abbreviations in a description: "The item doesn't exist" is enough.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +                schema: ShopInternalErrorSchema,
This is covered as a general internal error, don't need this separately.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +        }
Don't wrap everything in a try catch, the error middleware will handle any undefined errors as internal errors with proper logging.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +            }
Instead of doing this loop twice - we should make these singular operations. One operation to get all the items requested. Then, loop over and check quantity. Then, check totalPointsRequired. Finally, update all the quantities as a single operation with $inc. If that works, you then deduct the total points required.

If we do this as a separate operation for each item it will be much slower for large orders.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +        }
This is a good example of where you don't need a custom error - if userOrder can be null, just throw an error like "User order missing". Since this shouldn't happen normally, it's fine.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +        }
This check isn't enough - we have to check all items in the order whenever the order is updated. The same goes for verifying points. Otherwise, this will let them add 1000 of the same item since it only checks the singular item. They won't be able to buy it, but that's not a good experience.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +
Again, whenever the order is gotten we need to verify it's still valid (checking quanity && points)

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +        // Validate item availability
It's good that we do validation here, but /qr isn't the only thing that should do it. Make this functionality into a shared function so that it can be used for all endpoints to validate the order is still valid, and change it if not.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +        const qrCodeUrl = `hackillinois://shop?userId=${userId}`;
This is not sufficient - use the user qr code generation. We need a qr that expires and can't just be generated by another user. With this logic I could make a qr for any arbitrary user and redeem their prize as them.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.ts
> +            },
Remove

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +    await Models.AttendeeProfile.deleteMany({});
You don't need to do this - this is done automatically.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +    });
This test is testing for an internal server error - we likely should have that error.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +            { quantity: [11] }, // TESTER_SHOP_ITEM presumably has 10 quantity
Instead of hardcoding this, do `TESTER_SHOP_ITEM.quanity + 1`

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +        const updatedItem2 = await Models.ShopItem.findOne({ itemId: secondItem.itemId });
you can make this code much nicer by just querying both items at once

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +        expect(updatedOrder?.quantity[0]).toBe(3);
don't hardcode numbers

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +        await postAsAttendee("/shop/cart/expensive-item").expect(StatusCode.ClientErrorPaymentRequired);
you shouldn't be checking just status code - also check the error returned. See other tests for reference.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +        await postAsAttendee("/shop/cart/test-item-1").expect(StatusCode.SuccessOK);
this depends on the other endpoint. While it is good to test both of these in one test, you should have at least one test that does not rely on the other endpoint. Otherwise, both of these tests will fail.

2025-01-31 16:30 UTC, Timothy-Gonzalez commented on src/services/shop/shop-router.test.ts
> +        await delAsAttendee("/shop/cart/test-item-1").expect(StatusCode.ServerErrorInternal);
this shouldn't be possible - internal errors should only happen if something goes wrong, not if a user does something normal

2025-02-02 19:45 UTC, Timothy-Gonzalez approved these changes

2025-02-02 19:46 UTC, merged