Dev/alex/auth service 2.0 : "auth/roles/list/:role"
HackIllinois/adonix pull request #63
Opened 2023-10-01 17:45 UTC by aletya

In /src/services/auth/auth-lib.ts, added a function getUsersWithRole which takes in the role to filter for and returns a string[] of ids.
In src/services/auth/auth-router.ts, added route "auth/roles/list/:role", which get all users that have a certain role, returning a string[] of ids.

2023-10-01 18:24 UTC, AydanPirani requested changes
Left a few small nits, should be good to go afterwards!

2023-10-01 18:24 UTC, AydanPirani commented on src/services/auth/auth-lib.ts
> +	// Makse a reference to the roles collection
Typo

2023-10-01 18:24 UTC, AydanPirani commented on src/services/auth/auth-lib.ts
> +	//now make a mongodb query that iterates thru and check which ones have the role
Capitalize comments please, and comments should be a bit more formal... i.e "thru" to "through"

2023-10-01 18:24 UTC, AydanPirani commented on src/services/auth/auth-lib.ts
> +	const queryCriteria : { roles: { $in: string[] } } = { roles: { $in: [role] } };
`{ roles: { $in: string[] } }` --> Create/use a pre-defined type instead. I think you can use a `Filter<Document` instead, which makes this cleaner

2023-10-01 18:24 UTC, AydanPirani commented on src/services/auth/auth-lib.ts
> +	const idArray : string[] = (result).map((user : RolesSchema) => {
Why parenthesis around result?

2023-10-01 18:24 UTC, AydanPirani commented on src/services/auth/auth-router.ts
> +authRouter.get("/roles/list/:role", async (req: Request, res: Response) => {
`role` should be capitalized in the query params, so :role -> :ROLE

2023-10-01 18:24 UTC, AydanPirani commented on src/services/auth/auth-router.ts
> +		return res.status(Constants.BAD_REQUEST).send({ error: "Role parameter is missing" });
`error: InvalidParams`

2023-10-01 19:05 UTC, aletya commented
Fixed pr comments

2023-10-01 20:57 UTC, AydanPirani commented on src/services/auth/auth-router.ts
> +	const ROLE: string | undefined = req.params.ROLE?.toString();
sorry for the confusion! role in your code should be lowercase, but :ROLE should be uppercase.

So something like `const role: string | undefined = req.params.ROLE;

2023-10-01 21:00 UTC, AydanPirani requested changes
Few more changes, then we're good to go!

2023-10-01 21:00 UTC, AydanPirani commented on src/services/auth/auth-router.ts
> +	const ROLE: string | undefined = req.params.ROLE?.toString();
Sorry for the confusion! 

role in code should be lowercase, but caps in the route.

For example: 

`const role: string | undefined = req.params.ROLE;` (also dw abt the toString function I think)

2023-10-01 21:00 UTC, AydanPirani commented on src/services/auth/auth-lib.ts
> +	//array of strings for id, will be the return value of this funciton
Also capitalize all these comments

2023-10-01 21:00 UTC, AydanPirani commented on src/services/auth/auth-lib.ts
> +	};*/
Remove commented-out code

2023-10-01 21:00 UTC, AydanPirani commented on src/services/auth/auth-router.ts
> +		return res.status(Constants.SUCCESS).send({ data: users });
Super small nit, but change `data: users` to `userIds: users`

2023-10-02 00:07 UTC, AydanPirani commented
Looks good to me! Thanks for working on this :)

2023-10-02 00:09 UTC, aletya commented
Yay first pr/push! Thanks for the comments

On Sun, Oct 1, 2023 at 7:07 PM Aydan Pirani ***@***.***>
wrote:

> Looks good to me! Thanks for working on this :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HackIllinois/adonix/pull/63#issuecomment-1742248926>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHY4DPCMEGBZTRXQA7RDZJ3X5IAVRANCNFSM6AAAAAA5OPGKUI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-02 06:41 UTC, AydanPirani approved these changes
Feel free to merge whenever :)

2023-10-02 17:52 UTC, merged